name: SonarQube
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4
    #   - name: Set up JDK 21
    #     uses: actions/setup-java@v4
    #     with:
    #       distribution: 'corretto'
    #       java-version: '21'
    #       cache: maven
    #   - name: Cache SonarQube packages
    #     uses: actions/cache@v4
    #     with:
    #       path: ~/.sonar/cache
    #       key: ${{ runner.os }}-sonar
    #       restore-keys: |
    #         ${{ runner.os }}-sonar
    #   - name: Cache Maven packages
    #     uses: actions/cache@v4
    #     with:
    #       path: ~/.m2
    #       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    #       restore-keys: ${{ runner.os }}-m2
    #   - name: Run Maven with SonarQube
    #     run: |
    #       mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
    #       -Dsonar.projectKey=basesonarqubepoc_sonarqubeconfirm \
    #       -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
    #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    #   - name: SonarQube Quality Gate
    #     uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #   - name: Official SonarQube Scan
    #     uses: SonarSource/sonarqube-scan-action@v5.1.0
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.1.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}