name: SonarQube Analysis (Standalone)

on:
  push:
    branches:
      - main
  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run SonarQube Analysis with Latest Plugin
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar \
            -Dsonar.projectKey=test_project \
            -Dsonar.sources=src \
            -Dsonar.language=java \
            -Dsonar.host.url=""