name: SonarQube Analysis (Standalone)

on:
  push:
    branches:
      - main
  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Download SonarScanner CLI from GitHub Releases
        run: |
          wget -O sonar-scanner-cli.zip https://github.com/SonarSource/sonar-scanner-cli/releases/latest/download/sonar-scanner-cli.zip
          unzip sonar-scanner-cli.zip

      - name: Run SonarQube Scanner (No Server)
        run: |
          java -jar sonar-scanner-cli.jar \
            -Dsonar.projectKey=test_project \
            -Dsonar.sources=src \
            -Dsonar.language=java
