name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    services:
      sonar:
        image: sonarqube:latest
        options: >-
          -p 9002:9000
        ports:
          - 9002:9000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SonarQube analysis
        run: |
          curl -u ${{ secrets.GITACTION_SONAR_TOKEN }}: -X POST "http://localhost:9002/api/projects/create?name=MyProject&project=MyProjectKey"
          
          sonar-scanner \
            -Dsonar.projectKey=MyProjectKey \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9002 \
            -Dsonar.login=${{ secrets.GITACTION_SONAR_TOKEN }}
